Repository ansible-collections/community.aws, pull requests merged in 2021-12, with the labels that each got.

#816 Disable ssm connection tests
  tests/integration/targets/connection_aws_ssm/aliases
Labels: gate

#779 Create ec2_asg_scheduled_action module
  meta/runtime.yml
  plugins/modules/ec2_asg_scheduled_action.py
  test-requirements.txt
  tests/integration/requirements.txt
  tests/integration/targets/ec2_asg_scheduled_action/aliases
  tests/integration/targets/ec2_asg_scheduled_action/defaults/main.yml
  tests/integration/targets/ec2_asg_scheduled_action/meta/main.yml
  tests/integration/targets/ec2_asg_scheduled_action/tasks/main.yml
Labels: new_plugin, new_module, integration, module, tests, needs_triage, community_review, plugins, gate, backport-2

#763 aws_ssm connection: add SSE encryption parameters.
  changelogs/fragments/763-aws_ssm_connection-add-sse-parameters.yml
  plugins/connection/aws_ssm.py
  tests/integration/targets/connection_aws_ssm/aliases
  tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/defaults/main.yml
  tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/tasks/main.yml
  tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/tasks/redhat.yml
  tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2
  tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/s3_vars_to_delete.yml.j2
  tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_teardown/tasks/main.yml
Labels: new_contributor, feature, connection, integration, tests, needs_triage, community_review, plugins, gate, backport-2

#821 wafv2_web_acl: more examples
  plugins/modules/wafv2_web_acl.py
Labels: docs, gate, backport-2

#822 iam_user password management support
  changelogs/fragments/822-add-password-support-iam_user.yml
  plugins/modules/iam_user.py
  tests/integration/targets/iam_user/defaults/main.yml
  tests/integration/targets/iam_user/tasks/main.yml
Labels: gate, backport-2

#837 Make deprecated updates in dynamodbo_table module fail
  changelogs/fragments/837-make-deprecated-dynamodb_table-updates-fail.yml.yml
  plugins/modules/dynamodb_table.py
  tests/integration/targets/dynamodb_table/defaults/main.yml
  tests/integration/targets/dynamodb_table/tasks/main.yml
  tests/integration/targets/dynamodb_table/tasks/test_pay_per_request.yml
Labels: gate

#838 Make deprecated keys_attr param ignored in aws_kms_info
  changelogs/fragments/838-ignore-deprecated-param-aws_kms_info.yml
  plugins/modules/aws_kms_info.py
Labels: gate
