Repository ansible-collections/community.aws, pull requests merged in 2021-11, with the labels that each got.

#792 Add missing entries to AWS action group
  changelogs/fragments/557-action_group-missing-entry.yml
  meta/runtime.yml
Labels: bug, needs_triage, community_review, gate

#797 Fix docs issues.
  plugins/modules/ec2_elb_info.py
  plugins/modules/iam.py
  plugins/modules/rds.py
Labels: gate

#799 route53: fix empty result set
  changelogs/fragments/798-fix-route53-empty-result.yaml
  plugins/modules/route53.py
  tests/integration/targets/route53/tasks/main.yml
Labels: gate

#802 Route53: fix diff mode when state: absent
  changelogs/fragments/802-fix-diif-mode.yml
  plugins/modules/route53.py
  tests/integration/targets/route53/tasks/main.yml
Labels: gate

#804 Add wildcard to credentials file in .gitignore
  tests/.gitignore
Labels: gate

#785 added clarification on SSE and `kms_master_key_id`
  plugins/modules/sqs_queue.py
Labels: module, needs_triage, community_review, plugins, docs, gate

#801 fix delete records without TTL
  changelogs/fragments/801-fix-delete-without-ttl.yml
  plugins/modules/route53.py
  tests/integration/targets/route53/tasks/main.yml
Labels: gate

#480 Add Python and Glue version parameters, add check mode
  changelogs/fragments/480-aws_glue_job-python-glue-version.yml
  plugins/modules/aws_glue_job.py
  tests/integration/targets/aws_glue_job/aliases
  tests/integration/targets/aws_glue_job/defaults/main.yml
  tests/integration/targets/aws_glue_job/tasks/main.yml
Labels: feature, integration, module, tests, community_review, plugins, gate

#809 [3.0.0] Bump minimal botocore version to 1.19.0
  README.md
  changelogs/fragments/809-botocore-1-19-0.yml
  plugins/modules/aws_s3_bucket_info.py
  requirements.txt
  tests/integration/constraints.txt
  tests/integration/targets/setup_botocore_pip/defaults/main.yml
  tests/unit/constraints.txt
Labels: gate

#811 add patchback configs
  .github/patchback.yml
Labels: gate

#813 Fix route53_info max_items / type being ignored
  changelogs/fragments/813-route53_info-fix-max_items.yml
  plugins/modules/route53_info.py
  tests/integration/targets/route53/tasks/main.yml
Labels: gate
