Repository ansible-collections/community.aws, pull requests merged in 2021-05, with the labels that each got.

#581 Update README with new python and botocore requirements
  README.md
Labels: gate

#564 Route53 retry/waiter tweaks
  changelogs/564-route53-retries.yml
  plugins/modules/route53.py
Labels: gate

#579 Remove ec2_instance modules and tests
  changelogs/fragments/migrate_ec2_instance.yml
  docs/community.aws.ec2_instance_info_module.rst
  docs/community.aws.ec2_instance_module.rst
  meta/runtime.yml
  plugins/modules/ec2_instance.py
  plugins/modules/ec2_instance_facts.py
  plugins/modules/ec2_instance_info.py
  plugins/modules/ec2_launch_template.py
  tests/integration/targets/ec2_instance/aliases
  tests/integration/targets/ec2_instance/inventory
  tests/integration/targets/ec2_instance/main.yml
  tests/integration/targets/ec2_instance/meta/main.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/defaults/main.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/files/assume-role-policy.json
  tests/integration/targets/ec2_instance/roles/ec2_instance/meta/main.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/block_devices.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/checkmode_tests.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/cpu_options.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/default_vpc_tests.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/ebs_optimized.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/env_cleanup.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/env_setup.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/external_resource_attach.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/find_ami.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/iam_instance_role.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/instance_no_wait.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/main.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/security_group.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/tags_and_vpc_settings.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/termination_protection.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/termination_protection_wrapper.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/uptime.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/version_fail.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/version_fail_wrapper.yml
  tests/integration/targets/ec2_instance/runme.sh
  tests/integration/targets/ec2_launch_template/defaults/main.yml
  tests/sanity/ignore-2.9.txt
Labels: community_review, docs, feature, gate, integration, module, plugins, tests

#587 Update README, CONTRIBUTING.md: freenode -> libera.chat
  CONTRIBUTING.md
  README.md
Labels: community_review, docs, gate
