Repository ansible-collections/community.aws, pull requests merged in 2022-01, with the labels that each got.

#818 Fix short EKS cluster names
  changelogs/fragments/818-fix-eks-short-name.yml
  plugins/modules/aws_eks_cluster.py
  tests/integration/targets/aws_eks_cluster/defaults/main.yml
  tests/integration/targets/aws_eks_cluster/tasks/full_test.yml
Labels: gate, backport-2

#839 Remove deprecated Modules
  changelogs/fragments/14532-remove-deprecations.yml
  meta/runtime.yml
  plugins/modules/iam.py
  plugins/modules/rds.py
  tests/integration/targets/rds_instance/aliases
  tests/integration/targets/rds_instance/roles/rds_instance/defaults/main.yml
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.9.txt
Labels: gate

#851 aws_kms_info: Correct deprecation of keys_attr
  changelogs/fragments/838-ignore-deprecated-param-aws_kms_info.yml
  plugins/modules/aws_kms_info.py
Labels: gate

#794 Add abort multipart upload and expire obj del markers to s3 lifecycle
  changelogs/fragments/794-s3_lifecycle_abort_expire.yml
  plugins/modules/s3_lifecycle.py
  tests/integration/targets/s3_lifecycle/tasks/main.yml
Labels: gate, backport-2

#866 Update contributor doc to add changelog section
  CONTRIBUTING.md
Labels: gate

#863 docs fix. clean up duplicated and unspecific requirements
  changelogs/fragments/863-requirements-doc-fix.yml
  plugins/modules/aws_msk_config.py
  plugins/modules/ecs_taskdefinition.py
Labels: backport-2, mergeit

#871 wafv2_web_acl_info doc fix
  plugins/modules/wafv2_web_acl_info.py
Labels: mergeit

#874 Release 3.0.1 commit
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/794-s3_lifecycle_abort_expire.yml
  changelogs/fragments/863-requirements-doc-fix.yml
  docs/community.aws.aws_kms_info_module.rst
  docs/community.aws.aws_msk_config_module.rst
  docs/community.aws.ecs_taskdefinition_module.rst
  docs/community.aws.s3_lifecycle_module.rst
  galaxy.yml
Labels: mergeit

#860 add missing password_reset_required parameter
  changelogs/fragments/860-add-missing-parameter.yml
  plugins/modules/iam_user.py
  tests/integration/targets/iam_user/tasks/main.yml
Labels: mergeit

#824 Add ec2_lc* integration tests
  plugins/modules/ec2_lc.py
  tests/integration/targets/ec2_lc/aliases
  tests/integration/targets/ec2_lc/defaults/main.yml
  tests/integration/targets/ec2_lc/meta/main.yml
  tests/integration/targets/ec2_lc/tasks/env_cleanup.yml
  tests/integration/targets/ec2_lc/tasks/env_setup.yml
  tests/integration/targets/ec2_lc/tasks/main.yml
  tests/integration/targets/ec2_lc/vars/main.yml
Labels: mergeit

#843 Add ability to manage resource policy for AWS Secrets Manager secrets
  changelogs/fragments/843-add_aws_secret_resource_policy_support.yml
  plugins/modules/aws_secret.py
  tests/integration/targets/aws_secret/tasks/basic.yml
  tests/integration/targets/aws_secret/templates/secret-policy.j2
Labels: mergeit

#790 ec2_lc: add volume throughput parameter support
  changelogs/fragments/790-ec2_lc-add-throughput-param-support.yml
  plugins/modules/ec2_lc.py
  tests/integration/targets/ec2_lc/tasks/main.yml
Labels: feature, module, community_review, small_patch, plugins, mergeit

#826 Respect wait parameter in elb_instance when adding/removing instances
  changelogs/fragments/825-fix-elb-wait.yml
  plugins/modules/elb_instance.py
Labels: backport-2, mergeit

#882 migrate from ansible.netcommon to ansible.utils
  test-requirements.txt
  tests/integration/requirements.txt
  tests/integration/targets/ec2_eip/tasks/main.yml
Labels: bug, new_contributor, integration, tests, needs_triage, community_review, plugins, mergeit

#857 Lambda - Wait before updating
  changelogs/fragments/857-lambda-wait-before.yml
  plugins/modules/execute_lambda.py
  plugins/modules/lambda.py
Labels: bug, module, community_review, plugins, backport-2, mergeit, backport-3

#896 Cleanup unused imports
  plugins/modules/aws_glue_job.py
  plugins/modules/cloudfront_info.py
  plugins/modules/rds_option_group_info.py
Labels: feature, owner_pr, module, needs_triage, community_review, plugins, mergeit, backport-3

#903 aws_acm: fix yamllint errors in docs section
  plugins/modules/aws_acm.py
Labels: owner_pr, module, community_review, plugins, docs, mergeit, backport-3

#901 Improve doc of ec2_launch_template module
  plugins/modules/ec2_launch_template.py
Labels: has_issue, module, community_review, small_patch, plugins, docs, mergeit, backport-3

#881 Fix cloudfront_distribution s3_origin_access_identity_enabled bug
  changelogs/fragments/881-cloudfront-bug.yml
  plugins/modules/cloudfront_distribution.py
Labels: bug, module, community_review, plugins, backport-2, mergeit, backport-3

#897 Bump release to 4.0.0-dev0
  galaxy.yml
Labels: feature, needs_triage, community_review, small_patch, mergeit, do_not_backport

#898 [Breaking Change] Final removal of original boto SDK
  changelogs/fragments/898-boto-removal.yaml
  plugins/modules/aws_direct_connect_virtual_interface.py
  plugins/modules/ec2_eip.py
  plugins/modules/ecs_service.py
  plugins/modules/ecs_taskdefinition.py
  plugins/modules/iam_saml_federation.py
  plugins/modules/iam_server_certificate.py
  plugins/modules/rds_param_group.py
  plugins/modules/route53.py
  requirements.txt
  scripts/inventory/__init__.py
  scripts/inventory/ec2.ini
  scripts/inventory/ec2.py
  test-requirements.txt
  tests/integration/requirements.txt
  tests/integration/targets/script_inventory_ec2/aliases
  tests/integration/targets/script_inventory_ec2/ec2.sh
  tests/integration/targets/script_inventory_ec2/inventory_diff.py
  tests/integration/targets/script_inventory_ec2/runme.sh
  tests/unit/requirements.txt
Labels: module, tests, needs_triage, community_review, plugins, mergeit, do_not_backport
