Repository ansible-collections/community.aws, pull requests merged in 2023-05, with the labels that each got.

#1798 black - aws_ssm
  changelogs/fragments/1798-aws_ssm-black.yml
  plugins/connection/aws_ssm.py
  tests/integration/targets/connection_aws_ssm_addressing/aliases
  tests/integration/targets/connection_aws_ssm_cross_region/aliases
  tests/integration/targets/connection_aws_ssm_encrypted_s3/aliases
  tests/integration/targets/connection_aws_ssm_endpoint/aliases
  tests/integration/targets/connection_aws_ssm_fedora/aliases
  tests/integration/targets/connection_aws_ssm_profile/aliases
  tests/integration/targets/connection_aws_ssm_ssm_document/aliases
  tests/integration/targets/connection_aws_ssm_vars/aliases
Labels: mergeit

#1803 cloudfront_distribution - fix version added for not-backported features
  changelogs/fragments/version_added.yml
  plugins/modules/cloudfront_distribution.py
Labels: mergeit

#1788 s3_lifecycle - fix invalid value type for transitions list
  changelogs/fragments/20230424-s3_lifecycle.yml
  plugins/modules/s3_lifecycle.py
  tests/integration/targets/s3_lifecycle/tasks/main.yml
Labels: mergeit, backport-5

#1790 cloudformation_stack_set - Add a waiter to ensure that running operations against existing stacksets complete
  changelogs/fragments/20230424-cloudformation_stack_set.yml
  plugins/modules/cloudformation_stack_set.py
  tests/integration/targets/cloudformation_stack_set/tasks/main.yml
Labels: mergeit

#1807 [backport] [stable-5] s3_lifecycle - fix invalid value type for transitions list (#1788)
  changelogs/fragments/20230424-s3_lifecycle.yml
  plugins/modules/s3_lifecycle.py
  tests/integration/targets/s3_lifecycle/tasks/main.yml
Labels: mergeit

#1800 fix/elbv2-tg: KeyError when getting ProtocolVersion
  changelogs/fragments/1800-elb_target_group_property.yml
  plugins/modules/elb_target_group.py
Labels: mergeit, backport-5

#1805 Prepare final 4.x release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1576-defaults.yml
  changelogs/fragments/1757-config_rule-evaluation-mode.yml
  changelogs/fragments/iam_access_key_docs_fix.yml
  changelogs/fragments/sns_topic-cross-account.yml
  galaxy.yml
Labels: mergeit

#1808 [backport] [stable-5] fix/elbv2-tg: KeyError when getting ProtocolVersion
  changelogs/fragments/1800-elb_target_group_property.yml
  plugins/modules/elb_target_group.py
Labels: mergeit

#1804 Prepare release 5.5.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1736-elb_target_group_property.yml
  changelogs/fragments/1757-config_rule-evaluation-mode.yml
  changelogs/fragments/1761-msk_cluster-fix-authentication.yml
  changelogs/fragments/1763-ec2-launch-template-add-version-description.yml
  changelogs/fragments/1771-remote-access.yml
  changelogs/fragments/1797-s3-acls.yml
  changelogs/fragments/1800-elb_target_group_property.yml
  changelogs/fragments/20230424-cloudformation_stack_set.yml
  changelogs/fragments/20230424-s3_lifecycle.yml
  changelogs/fragments/elasticache_info-ignore-CacheClusterNotFound-when-reading-tags.yaml
  galaxy.yml
Labels: mergeit

#1786 aws_config_delivery_channel - Add support for KMS encryption
  changelogs/fragments/20230424-config-delivery-channel.yml
  plugins/modules/config_delivery_channel.py
  tests/integration/targets/config/defaults/main.yaml
  tests/integration/targets/config/tasks/main.yaml
  tests/integration/targets/config/templates/config-kms-policy.json.j2
Labels: mergeit

#1809 Merge 5.5.0 and 4.5.1 release info into main
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1736-elb_target_group_property.yml
  changelogs/fragments/1757-config_rule-evaluation-mode.yml
  changelogs/fragments/1761-msk_cluster-fix-authentication.yml
  changelogs/fragments/1763-ec2-launch-template-add-version-description.yml
  changelogs/fragments/1771-remote-access.yml
  changelogs/fragments/1797-s3-acls.yml
  changelogs/fragments/1800-elb_target_group_property.yml
  changelogs/fragments/20230424-cloudformation_stack_set.yml
  changelogs/fragments/20230424-s3_lifecycle.yml
  changelogs/fragments/elasticache_info-ignore-CacheClusterNotFound-when-reading-tags.yaml
Labels: mergeit

#1813 Prepare 6.0.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1435-connection-attempt-timeout.yml
  changelogs/fragments/1551-ecs_ecr-sort_json_policy.yml
  changelogs/fragments/1555-wafv2_rule_group_info.yml
  changelogs/fragments/1557-cloudfront-add-origin-shield.yml
  changelogs/fragments/1634-networkfirewall_rule_group-tests.yml
  changelogs/fragments/1643-codebuild_project.yml
  changelogs/fragments/1730-ses-identity-fix-clearing-notification-topic.yml
  changelogs/fragments/1738-headers.yml
  changelogs/fragments/1753-cloudfront-add-http3.yml
  changelogs/fragments/1784-black.yml
  changelogs/fragments/1798-aws_ssm-black.yml
  changelogs/fragments/20221103-autoscaling_scheduled_action.yml
  changelogs/fragments/20230307-blueprint.yml
  changelogs/fragments/20230423-update_readme_and_runtime.yml
  changelogs/fragments/20230424-config-delivery-channel.yml
  changelogs/fragments/6.0.0.yml
  changelogs/fragments/853-aws_ssm-sudo.yml
  changelogs/fragments/ansible-user-agent-identification.yaml
  changelogs/fragments/botocore-tests.yml
  changelogs/fragments/cloudfront_integration_tests_activate.yaml
  changelogs/fragments/elasticache-use-up-to-date-node-type-in-example.yaml
  changelogs/fragments/fstring-1.yml
  changelogs/fragments/integration_tests_max_duration_increase.yaml
  changelogs/fragments/opensearch_info_example_key_name.yaml
  changelogs/fragments/python37.yml
  changelogs/fragments/release-6-botocore.yml
  changelogs/fragments/version_added.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit

#1816 Switch to Ansible Galaxy compatible requirements files for tests
  changelogs/fragments/test-reqs.yml
  tests/integration/requirements.yml
  tests/requirements.yml
  tests/unit/requirements.yml
Labels: mergeit, backport-5, backport-6
