Repository ansible-collections/community.aws, pull requests merged in 2023-06, with the labels that each got.

#1824 cloudfront_distribution: now honours the enabled setting
  changelogs/fragments/1823-cloudfront_distribution_always_created_enabled.yml
  plugins/modules/cloudfront_distribution.py
  tests/integration/targets/cloudfront_distribution/tasks/main.yml
Labels: mergeit, backport-5, backport-6

#1822 cloudfront_distribution: no longer crashes when waiting for completion of creation
  changelogs/fragments/255-cloudfront_distribution_create_wait_crash.yml
  plugins/modules/cloudfront_distribution.py
Labels: mergeit, backport-5, backport-6

#1833 Fix FQDN in EXAMPLES block for mq_* modules.
  changelogs/fragments/20230531-mq-fix_fqdn.yml
  plugins/modules/mq_broker.py
  plugins/modules/mq_broker_config.py
  plugins/modules/mq_broker_info.py
  plugins/modules/mq_user.py
  plugins/modules/mq_user_info.py
Labels: mergeit, backport-5, backport-6

#1838 [manual backport stable-5] cloudfront_distribution: no longer crashes when waiting for completion of creation (#1822)
  changelogs/fragments/255-cloudfront_distribution_create_wait_crash.yml
  plugins/modules/cloudfront_distribution.py
Labels: mergeit

#1826 dynamodb_table: secondary indexes are now created
  changelogs/fragments/1825-dynamodb-table-no-secondary-indexes.yml
  plugins/modules/dynamodb_table.py
  tests/integration/targets/dynamodb_table/defaults/main.yml
  tests/integration/targets/dynamodb_table/tasks/main.yml
Labels: mergeit, backport-5, backport-6

#1799 Add sanity, linters, changelog, black and units workflows
  .github/workflows/all_green_ckeck.yml
  .github/workflows/changelog.yml
  .github/workflows/changelog_and_linters.yml
  .github/workflows/darker-pr.yml
  .github/workflows/sanity.yml
  .github/workflows/units.yml
  .github/workflows/update-variables.yml
  changelogs/fragments/20230613-black.yml
  plugins/modules/cloudfront_distribution.py
  tests/unit/compat/mock.py
  tests/unit/compat/unittest.py
  tests/unit/mock/path.py
  tests/unit/mock/procenv.py
  tests/unit/plugins/connection/test_aws_ssm.py
  tests/unit/plugins/modules/conftest.py
  tests/unit/plugins/modules/test_directconnect_confirm_connection.py
  tests/unit/plugins/modules/test_ec2_win_password.py
  tests/unit/plugins/modules/utils.py
  tox.ini
Labels: mergeit

#1821 Issue 1819 cloudfront distribution origin s3 domain
  changelogs/fragments/1819-cloudfront-distribution-s3-domain-recognise.yaml
  plugins/modules/cloudfront_distribution.py
  tests/integration/targets/cloudfront_distribution/tasks/main.yml
Labels: mergeit, backport-5, backport-6

#1851 lint - cloudfront_distribution - apply black formatting
  changelogs/fragments/20230623-black-cloudfront.yml
  plugins/modules/cloudfront_distribution.py
Labels: mergeit

#1857 Preinstall requirements for tests and use GitHub as the source.
  .github/workflows/sanity.yml
  .github/workflows/units.yml
  changelogs/fragments/workflow-requirements.yml
Labels: mergeit

#1848 Various ARN handling fixes
  changelogs/fragments/1846-arn.yml
  plugins/modules/batch_compute_environment.py
  plugins/modules/ec2_launch_template.py
  plugins/modules/elasticache_info.py
  plugins/modules/iam_group.py
  plugins/modules/iam_role.py
  plugins/modules/msk_config.py
  plugins/modules/redshift.py
  plugins/modules/sns_topic.py
Labels: mergeit

#1859 CI test fixups
  changelogs/fragments/20230627-ci-fixup.yml
  tests/integration/targets/dynamodb_table/tasks/main.yml
  tests/integration/targets/ecs_cluster/tasks/main.yml
Labels: mergeit, backport-5, backport-6

#1844 Fix minor typo in mq_broker example users
  plugins/modules/mq_broker.py
Labels: mergeit, backport-6
