Repository ansible-collections/community.aws, pull requests merged in 2023-04, with the labels that each got.

#1757 config_rule - Fix Idempotency by Ignoring `EvaluationModes` Parameter
  changelogs/fragments/1757-config_rule-evaluation-mode.yml
  plugins/modules/config_rule.py
  tests/integration/targets/config/tasks/main.yaml
Labels: mergeit, backport-4, backport-5

#1763 Add version_description to ec2_launch_template
  changelogs/fragments/1763-ec2-launch-template-add-version-description.yml
  plugins/modules/ec2_launch_template.py
  tests/integration/targets/ec2_launch_template/tasks/versions.yml
Labels: new_contributor, feature, integration, module, tests, community_review, plugins, mergeit, backport-5

#1753 Add http3 support in cloudfront_distribution module
  changelogs/fragments/1753-cloudfront-add-http3.yml
  plugins/modules/cloudfront_distribution.py
  tests/integration/targets/cloudfront_distribution/tasks/main.yml
Labels: feature, integration, module, tests, community_review, plugins, mergeit, backport-5

#1767 elb_target_group: fix lost property AvailabilityZone
  changelogs/fragments/1736-elb_target_group_property.yml
  plugins/modules/elb_target_group.py
  tests/integration/targets/elb_target/tasks/ec2_target.yml
Labels: mergeit, backport-5

#1777 elasticache_info: ignore CacheClusterNotFound exeption during tag collect
  changelogs/fragments/elasticache_info-ignore-CacheClusterNotFound-when-reading-tags.yaml
  plugins/modules/elasticache_info.py
Labels: mergeit

#1773 eks_nodegroup - fixing remote access and added to integration tests
  changelogs/fragments/1771-remote-access.yml
  plugins/modules/eks_nodegroup.py
  tests/integration/targets/eks_nodegroup/tasks/cleanup.yml
  tests/integration/targets/eks_nodegroup/tasks/dependecies.yml
  tests/integration/targets/eks_nodegroup/tasks/full_test.yml
Labels: mergeit, backport-5

#1781 eks_nodegroup - fixing remote access and added to integration tests
  changelogs/fragments/1771-remote-access.yml
  plugins/modules/eks_nodegroup.py
  tests/integration/targets/eks_nodegroup/tasks/cleanup.yml
  tests/integration/targets/eks_nodegroup/tasks/dependecies.yml
  tests/integration/targets/eks_nodegroup/tasks/full_test.yml
Labels: mergeit

#1794 Update README.md and meta/runtime.yml to reflect our ansible core testing versions
  README.md
  changelogs/fragments/20230423-update_readme_and_runtime.yml
  meta/runtime.yml
Labels: mergeit
