Repository ansible-collections/community.aws, pull requests merged in 2023-07, with the labels that each got.

#1863 CI test fixups - Ansible milestone update
  changelogs/fragments/20230701-ci-fixup.yml
  tests/integration/targets/dynamodb_table/tasks/test_pay_per_request.yml
  tests/integration/targets/sts_assume_role/tasks/main.yml
Labels: mergeit, backport-5, backport-6

#1831 feat: add mq inventory plugin; addresses #1827
  plugins/inventory/aws_mq.py
  tests/integration/targets/inventory_aws_mq/aliases
  tests/integration/targets/inventory_aws_mq/meta/main.yml
  tests/integration/targets/inventory_aws_mq/playbooks/create_inventory_config.yml
  tests/integration/targets/inventory_aws_mq/playbooks/empty_inventory_config.yml
  tests/integration/targets/inventory_aws_mq/playbooks/populate_cache.yml
  tests/integration/targets/inventory_aws_mq/playbooks/setup_instance.yml
  tests/integration/targets/inventory_aws_mq/playbooks/tasks/find_broker.yml
  tests/integration/targets/inventory_aws_mq/playbooks/tasks/mq_instance_create.yml
  tests/integration/targets/inventory_aws_mq/playbooks/tasks/mq_instance_delete.yml
  tests/integration/targets/inventory_aws_mq/playbooks/test_invalid_aws_mq_inventory_config.yml
  tests/integration/targets/inventory_aws_mq/playbooks/test_inventory_cache.yml
  tests/integration/targets/inventory_aws_mq/playbooks/test_inventory_no_hosts.yml
  tests/integration/targets/inventory_aws_mq/playbooks/test_inventory_with_hostvars_prefix_suffix.yml
  tests/integration/targets/inventory_aws_mq/playbooks/test_populating_inventory.yml
  tests/integration/targets/inventory_aws_mq/playbooks/test_populating_inventory_with_constructed.yml
  tests/integration/targets/inventory_aws_mq/playbooks/vars/main.yml
  tests/integration/targets/inventory_aws_mq/runme.sh
  tests/integration/targets/inventory_aws_mq/templates/inventory.j2
  tests/integration/targets/inventory_aws_mq/templates/inventory_with_cache.j2
  tests/integration/targets/inventory_aws_mq/templates/inventory_with_constructed.j2
  tests/integration/targets/inventory_aws_mq/templates/inventory_with_hostvars_prefix_suffix.j2
  tests/unit/plugins/inventory/__init__.py
  tests/unit/plugins/inventory/test_aws_mq.py
Labels: mergeit, backport-6

#1866 DynamoDB - add waiter for secondary indexes
  changelogs/fragments/20230702-dynamodb_waiter.yml
  plugins/module_utils/dynamodb.py
  plugins/modules/dynamodb_table.py
Labels: mergeit, backport-6

#1872 Prep community.aws 5.5.1 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1823-cloudfront_distribution_always_created_enabled.yml
  changelogs/fragments/20230627-ci-fixup.yml
  changelogs/fragments/20230701-ci-fixup.yml
  changelogs/fragments/20230704-github_workflows.yml
  changelogs/fragments/255-cloudfront_distribution_create_wait_crash.yml
  changelogs/fragments/test-reqs.yml
  changelogs/fragments/tests-requirements.yml
  galaxy.yml
Labels: mergeit

#1876 community.aws 6.1.0 prep
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1819-cloudfront-distribution-s3-domain-recognise.yaml
  changelogs/fragments/1823-cloudfront_distribution_always_created_enabled.yml
  changelogs/fragments/1825-dynamodb-table-no-secondary-indexes.yml
  changelogs/fragments/1846-arn.yml
  changelogs/fragments/20230531-mq-fix_fqdn.yml
  changelogs/fragments/20230613-black.yml
  changelogs/fragments/20230627-ci-fixup.yml
  changelogs/fragments/20230701-ci-fixup.yml
  changelogs/fragments/20230702-dynamodb_waiter.yml
  changelogs/fragments/255-cloudfront_distribution_create_wait_crash.yml
  changelogs/fragments/6.0.0.yml
  changelogs/fragments/test-reqs.yml
  changelogs/fragments/tests-requirements.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#1877 Add transit-gateway-id parameter to ec2_vpc_vpn module
  changelogs/fragments/transit_gateway_to_vpn.yaml
  plugins/modules/ec2_vpc_vpn.py
  tests/integration/targets/ec2_vpc_vpn/tasks/main.yml
Labels: feature, integration, module, tests, community_review, plugins, mergeit, backport-6

#1889 CI - fix sanity and units tests
  .github/workflows/sanity.yml
  .github/workflows/units.yml
Labels: bug, needs_triage, community_review, python3, small_patch, mergeit

#1875 Update changelog to reflect the 5.5.1 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1823-cloudfront_distribution_always_created_enabled.yml
  changelogs/fragments/20230613-black.yml
  changelogs/fragments/20230627-ci-fixup.yml
  changelogs/fragments/20230701-ci-fixup.yml
  changelogs/fragments/255-cloudfront_distribution_create_wait_crash.yml
  changelogs/fragments/test-reqs.yml
  changelogs/fragments/tests-requirements.yml
Labels: needs_triage, community_review, docs, mergeit
