Repository ansible-collections/community.aws, pull requests merged in 2023-10, with the labels that each got.

#1966 Promote aws_region_info
  changelogs/fragments/migrate_aws_region_info.yml
  meta/runtime.yml
  plugins/modules/aws_region_info.py
  tests/integration/targets/aws_region_info/aliases
  tests/integration/targets/aws_region_info/main.yml
  tests/integration/targets/aws_region_info/meta/main.yml
  tests/integration/targets/aws_region_info/tasks/main.yml
Labels: mergeit

#1953 Promote iam_mfa_device_info
  changelogs/fragments/migrate_iam_mfa_device_info.yml
  meta/runtime.yml
  plugins/modules/iam_mfa_device_info.py
Labels: mergeit

#1965 Promote s3_bucket_info
  changelogs/fragments/migrate_s3_bucket_info.yml
  meta/runtime.yml
  plugins/modules/s3_bucket_info.py
  tests/integration/targets/s3_bucket_info/aliases
  tests/integration/targets/s3_bucket_info/defaults/main.yml
  tests/integration/targets/s3_bucket_info/meta/main.yml
  tests/integration/targets/s3_bucket_info/tasks/basic.yml
  tests/integration/targets/s3_bucket_info/tasks/bucket_ownership_controls.yml
  tests/integration/targets/s3_bucket_info/tasks/main.yml
Labels: mergeit

#1957 Promote iam_access_key and the corresponding _info module
  changelogs/fragments/migrate_iam_access_key.yml
  meta/runtime.yml
  plugins/modules/iam_access_key.py
  plugins/modules/iam_access_key_info.py
  tests/integration/targets/iam_access_key/aliases
  tests/integration/targets/iam_access_key/defaults/main.yml
  tests/integration/targets/iam_access_key/meta/main.yml
  tests/integration/targets/iam_access_key/tasks/main.yml
Labels: mergeit

#1958 Promote iam_password_policy
  changelogs/fragments/migrate_iam_password_policy.yml
  meta/runtime.yml
  plugins/modules/iam_password_policy.py
  tests/integration/targets/iam_password_policy/aliases
  tests/integration/targets/iam_password_policy/meta/main.yml
  tests/integration/targets/iam_password_policy/tasks/main.yaml
  tests/unit/plugins/modules/test_iam_password_policy.py
Labels: mergeit

#1959 Promote sts_assume_role
  changelogs/fragments/migrate_sts_assume_role.yml
  meta/runtime.yml
  plugins/modules/sts_assume_role.py
  tests/integration/targets/sts_assume_role/aliases
  tests/integration/targets/sts_assume_role/defaults/main.yml
  tests/integration/targets/sts_assume_role/meta/main.yml
  tests/integration/targets/sts_assume_role/tasks/main.yml
  tests/integration/targets/sts_assume_role/templates/policy.json.j2
Labels: mergeit

#1964 Prepare release 6.4.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1891_ecs-task-definition-add-runtime-platform.yml
  changelogs/fragments/20230906-galaxy.yml
  changelogs/fragments/20230906-route53_wait.yml
  changelogs/fragments/20230908-alias-cleanup.yml
  changelogs/fragments/botocore_params-cleanup.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#1968 [7.0.0] Bump botocore requirements
  README.md
  changelogs/fragments/botocore.yml
  changelogs/fragments/python37.yml
  plugins/module_utils/networkfirewall.py
  plugins/modules/dynamodb_table.py
  plugins/modules/ec2_launch_template.py
  plugins/modules/networkfirewall_policy.py
  plugins/modules/networkfirewall_rule_group.py
  plugins/modules/networkfirewall_rule_group_info.py
  plugins/modules/opensearch.py
  plugins/modules/opensearch_info.py
  plugins/modules/s3_lifecycle.py
  plugins/modules/wafv2_web_acl.py
  requirements.txt
  tests/config.yml
  tests/integration/constraints.txt
  tests/unit/constraints.txt
Labels: mergeit

#1886 mq_broker - fix creation with tags
  changelogs/fragments/1832-mq_broker_tags.yml
  plugins/modules/mq_broker.py
  tests/integration/targets/mq/defaults/main.yml
  tests/integration/targets/mq/tasks/broker_tests.yml
  tests/integration/targets/mq/tasks/main.yml
Labels: bug, integration, module, tests, needs_triage, community_review, plugins, mergeit, backport-6
