Repository ansible-collections/community.aws, pull requests merged in 2023-03, with the labels that each got.

#1716 ecs: integration test and new purge parameters
  changelogs/fragments/ecs_service_and_ecs_integration_test.yml
  plugins/modules/ecs_service.py
  tests/integration/targets/ecs_cluster/aliases
  tests/integration/targets/ecs_cluster/defaults/main.yml
  tests/integration/targets/ecs_cluster/meta/main.yml
  tests/integration/targets/ecs_cluster/tasks/01_create_requirements.yml
  tests/integration/targets/ecs_cluster/tasks/10_ecs_cluster.yml
  tests/integration/targets/ecs_cluster/tasks/20_ecs_service.yml
  tests/integration/targets/ecs_cluster/tasks/99_terminate_everything.yml
  tests/integration/targets/ecs_cluster/tasks/main.yml
Labels: bug, integration, module, tests, community_review, python3, plugins, mergeit, backport-5

#1680 ecs_service -- with force_new_deployment user can specify taskdef or not
  changelogs/fragments/1680-ecs_service-force_redeploy_taskdef_optional.yml
  plugins/modules/ecs_service.py
  tests/integration/targets/ecs_cluster/tasks/20_ecs_service.yml
Labels: feature, integration, module, tests, needs_triage, community_review, plugins, backport-5

#1734 Fix 'compatibility' typo
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1734-typo.yml
Labels: mergeit, backport-4, backport-5

#1740 Prepare release 5.3.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1426-docs_update_ecs_taskdefinition.yml
  changelogs/fragments/1574-ssm-parameter-support-for-tags.yml
  changelogs/fragments/1591-eks-add-tags-cluster.yml
  changelogs/fragments/1606-s3_lifecycle_add_number_of_versions_to_retain.yml
  changelogs/fragments/1619-add-s3-bucket-endpoint-url-var-for-private-network-vpc-interface-endpoints.yml
  changelogs/fragments/1628-secretsmanager_secret-overwrite.yml
  changelogs/fragments/1680-ecs_service-force_redeploy_taskdef_optional.yml
  changelogs/fragments/1690-fix-copying-empty-file.yml
  changelogs/fragments/1693-sns_topic.yml
  changelogs/fragments/1726-ssm_connection-vars_tests.yml
  changelogs/fragments/1728_remove_state.yml
  changelogs/fragments/1734-typo.yml
  changelogs/fragments/20221125-sqs-high-throughput.yml
  changelogs/fragments/20230204-sanity.yml
  changelogs/fragments/514-aws_ssm-env_vars.yml
  changelogs/fragments/551-iam_role-policy_documents.yml
  changelogs/fragments/827-secretsmanager_secret-replication.yml
  changelogs/fragments/972-sns_topic-add_tags.yaml
  changelogs/fragments/ecs_service_and_ecs_integration_test.yml
  changelogs/fragments/eks.yml
  changelogs/fragments/eks_release.yml
  changelogs/fragments/iam_access_key_docs_fix.yml
  changelogs/fragments/sns_topic-cross-account.yml
  galaxy.yml
Labels: mergeit

#1741 Add initial configuration for darker/black
  pyproject.toml
Labels: mergeit

#1739 Update lightsail blueprint
  changelogs/fragments/20230307-blueprint.yml
  tests/integration/targets/lightsail/tasks/main.yml
Labels: mergeit

#1743 fix link README
  README.md
Labels: mergeit

#1742 Merge changelogs from 4.5.0, 5.2.0 and 5.3.0 into main
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1426-docs_update_ecs_taskdefinition.yml
  changelogs/fragments/1574-ssm-parameter-support-for-tags.yml
  changelogs/fragments/1591-eks-add-tags-cluster.yml
  changelogs/fragments/1601-ecs_service-support_constraints_and_strategy_update.yml
  changelogs/fragments/1606-s3_lifecycle_add_number_of_versions_to_retain.yml
  changelogs/fragments/1616-aws_ssm-new-regions.yml
  changelogs/fragments/1619-add-s3-bucket-endpoint-url-var-for-private-network-vpc-interface-endpoints.yml
  changelogs/fragments/1623-ecs_ecr-add-kms-config.yml
  changelogs/fragments/1624-s3-lifecycle-idempotent.yml
  changelogs/fragments/1625-ecs_service-support-load-balancer-update.yml
  changelogs/fragments/1627-ssm_parameter-KeyError-when-adding-description.yml
  changelogs/fragments/1628-secretsmanager_secret-overwrite.yml
  changelogs/fragments/1633-s3-url-address-style.yml
  changelogs/fragments/1642-ssm_parameter.yml
  changelogs/fragments/1660-aws_ssm-logging.yml
  changelogs/fragments/1663-aws_ssm-client.yml
  changelogs/fragments/1664-aws_ssm-transport_command.yml
  changelogs/fragments/1676-changelog.yml
  changelogs/fragments/1680-ecs_service-force_redeploy_taskdef_optional.yml
  changelogs/fragments/1690-fix-copying-empty-file.yml
  changelogs/fragments/1693-sns_topic.yml
  changelogs/fragments/1726-ssm_connection-vars_tests.yml
  changelogs/fragments/1728_remove_state.yml
  changelogs/fragments/1734-typo.yml
  changelogs/fragments/20221125-sqs-high-throughput.yml
  changelogs/fragments/20230112-aws_ssm-tests.yml
  changelogs/fragments/20230113-encryption.yml
  changelogs/fragments/20230204-sanity.yml
  changelogs/fragments/514-aws_ssm-env_vars.yml
  changelogs/fragments/551-iam_role-policy_documents.yml
  changelogs/fragments/558-ssm_connection-invalid-literal.yml
  changelogs/fragments/770-ecs-capacity-provider-strategy.yml
  changelogs/fragments/827-secretsmanager_secret-replication.yml
  changelogs/fragments/876-aws_ssm_connection_ssm_document.yml
  changelogs/fragments/972-sns_topic-add_tags.yaml
  changelogs/fragments/aws_ssm-facts.yml
  changelogs/fragments/ecs_service_and_ecs_integration_test.yml
  changelogs/fragments/eks.yml
  changelogs/fragments/eks_release.yml
  changelogs/fragments/iam_access_key_docs_fix.yml
  changelogs/fragments/iam_role_purge_policy.yml
  changelogs/fragments/sns_topic-cross-account.yml
Labels: mergeit

#1744 [6.0.0] Bump botocore requirements
  README.md
  changelogs/fragments/python37.yml
  changelogs/fragments/release-6-botocore.yml
  plugins/modules/opensearch.py
  plugins/modules/opensearch_info.py
  requirements.txt
  tests/integration/constraints.txt
  tests/integration/targets/ec2_launch_template/meta/main.yml
  tests/integration/targets/ec2_launch_template/tasks/instance-metadata.yml
  tests/integration/targets/ecs_cluster/meta/main.yml
  tests/integration/targets/ecs_cluster/tasks/20_ecs_service.yml
  tests/integration/targets/ecs_cluster/tasks/99_terminate_everything.yml
  tests/integration/targets/networkfirewall_rule_group/meta/main.yml
  tests/integration/targets/networkfirewall_rule_group/tasks/main.yml
  tests/integration/targets/networkfirewall_rule_group/tasks/stateful.yml
  tests/integration/targets/opensearch/meta/main.yml
  tests/integration/targets/opensearch/tasks/main.yml
  tests/integration/targets/opensearch/tasks/test_create_cert.yml
  tests/integration/targets/setup_botocore_pip/defaults/main.yml
  tests/unit/constraints.txt
Labels: mergeit

#1724 lightsail: add support for firewall ports and snapshot management
  meta/runtime.yml
  plugins/modules/lightsail.py
  plugins/modules/lightsail_snapshot.py
  tests/integration/targets/lightsail/tasks/main.yml
  tests/integration/targets/lightsail_snapshot/aliases
  tests/integration/targets/lightsail_snapshot/defaults/main.yml
  tests/integration/targets/lightsail_snapshot/meta/main.yml
  tests/integration/targets/lightsail_snapshot/tasks/main.yml
Labels: mergeit

#1730 ses: fix clearing notification topic
  changelogs/fragments/1730-ses-identity-fix-clearing-notification-topic.yml
  plugins/modules/ses_identity.py
  tests/integration/targets/ses_identity/tasks/main.yaml
Labels: mergeit

#1733 sns: Add parameters for fifo topics
  changelogs/fragments/1733-sns-publish-to-fifo-topics.yml
  plugins/modules/sns.py
  tests/integration/targets/sns/defaults/main.yml
  tests/integration/targets/sns/tasks/main.yml
Labels: mergeit, backport-5

#1750 automatically update variables
  .github/workflows/update-variables.yml
Labels: mergeit

#488 Support new enableExecuteCommand options for ECS service
  changelogs/fragments/488-ecs_service-support_exec.yml
  plugins/modules/ecs_service.py
  tests/integration/targets/ecs_cluster/tasks/01_create_requirements.yml
  tests/integration/targets/ecs_cluster/tasks/20_ecs_service.yml
Labels: new_contributor, feature, integration, module, tests, community_review, plugins, mergeit, backport-5

#432 New Module: Amazon MQ
  meta/runtime.yml
  plugins/modules/mq_broker.py
  plugins/modules/mq_broker_config.py
  plugins/modules/mq_broker_info.py
  plugins/modules/mq_user.py
  plugins/modules/mq_user_info.py
  tests/integration/targets/mq/aliases
  tests/integration/targets/mq/defaults/main.yml
  tests/integration/targets/mq/files/broker_cfg.1.xml
  tests/integration/targets/mq/files/broker_cfg.1a.xml
  tests/integration/targets/mq/files/broker_cfg.2.xml
  tests/integration/targets/mq/meta/main.yml
  tests/integration/targets/mq/tasks/broker_cleanup.yml
  tests/integration/targets/mq/tasks/broker_config_tests.yml
  tests/integration/targets/mq/tasks/broker_delete_tests.yml
  tests/integration/targets/mq/tasks/broker_tests.yml
  tests/integration/targets/mq/tasks/broker_user_info_tests.yml
  tests/integration/targets/mq/tasks/broker_user_tests.yml
  tests/integration/targets/mq/tasks/env_cleanup.yml
  tests/integration/targets/mq/tasks/env_setup.yml
  tests/integration/targets/mq/tasks/main.yml
  tests/integration/targets/mq/vars/main.yml
Labels: new_plugin, new_module, new_contributor, integration, module, tests, community_review, plugins, mergeit

#1758 Prepare release 5.4.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1733-sns-publish-to-fifo-topics.yml
  changelogs/fragments/488-ecs_service-support_exec.yml
  galaxy.yml
Labels: mergeit

#1759 Merge in 5.4.0 changelogs
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1733-sns-publish-to-fifo-topics.yml
  changelogs/fragments/488-ecs_service-support_exec.yml
Labels: mergeit

#1760 Add formatting linter
  .github/workflows/darker-pr.yml
Labels: mergeit
