Repository ansible-collections/community.aws, pull requests merged in 2023-09, with the labels that each got.

#1904 Add route53_wait module
  changelogs/fragments/1904-route53_wait.yml
  meta/runtime.yml
  plugins/modules/route53_wait.py
  tests/integration/targets/route53_wait/aliases
  tests/integration/targets/route53_wait/tasks/main.yml
  tests/unit/plugins/modules/test_route53_wait.py
Labels: new_plugin, new_module, has_issue, integration, module, tests, community_review, plugins, mergeit, backport-6

#1928 Fix version_added for route53_wait
  changelogs/fragments/20230906-route53_wait.yml
  plugins/modules/route53_wait.py
Labels: mergeit, backport-6

#1930 Add description to galaxy.yml
  README.md
  changelogs/fragments/20230906-galaxy.yml
  galaxy.yml
Labels: mergeit, backport-5, backport-6

#1892 feat: adds platform config to task definition to support ARM
  changelogs/fragments/1891_ecs-task-definition-add-runtime-platform.yml
  plugins/modules/ecs_taskdefinition.py
  tests/integration/targets/ecs_cluster/tasks/20_ecs_service.yml
Labels: new_contributor, feature, integration, module, tests, community_review, plugins, mergeit, backport-6

#1945 Promote iam_group module
  changelogs/fragments/migrate_iam_group.yml
  meta/runtime.yml
  plugins/modules/iam_group.py
  tests/integration/targets/iam_group/aliases
  tests/integration/targets/iam_group/defaults/main.yml
  tests/integration/targets/iam_group/meta/main.yml
  tests/integration/targets/iam_group/tasks/main.yml
Labels: mergeit

#1954 Promote iam_managed_policy module.
  changelogs/fragments/migrate_iam_managed_policy.yml
  meta/runtime.yml
  plugins/modules/iam_managed_policy.py
  tests/integration/targets/iam_managed_policy/aliases
  tests/integration/targets/iam_managed_policy/defaults/main.yml
  tests/integration/targets/iam_managed_policy/meta/main.yml
  tests/integration/targets/iam_managed_policy/tasks/main.yml
Labels: mergeit

#1948 Migrate modules iam_role and iam_role_info to amazon.aws
  changelogs/fragments/20230915_migrate_iam_role_and_iam_role_info.yml
  meta/runtime.yml
  plugins/modules/iam_role.py
  plugins/modules/iam_role_info.py
  tests/integration/targets/iam_role/aliases
  tests/integration/targets/iam_role/defaults/main.yml
  tests/integration/targets/iam_role/files/deny-all-a.json
  tests/integration/targets/iam_role/files/deny-all-b.json
  tests/integration/targets/iam_role/files/deny-all.json
  tests/integration/targets/iam_role/files/deny-assume.json
  tests/integration/targets/iam_role/meta/main.yml
  tests/integration/targets/iam_role/tasks/boundary_policy.yml
  tests/integration/targets/iam_role/tasks/complex_role_creation.yml
  tests/integration/targets/iam_role/tasks/creation_deletion.yml
  tests/integration/targets/iam_role/tasks/description_update.yml
  tests/integration/targets/iam_role/tasks/inline_policy_update.yml
  tests/integration/targets/iam_role/tasks/main.yml
  tests/integration/targets/iam_role/tasks/max_session_update.yml
  tests/integration/targets/iam_role/tasks/parameter_checks.yml
  tests/integration/targets/iam_role/tasks/policy_update.yml
  tests/integration/targets/iam_role/tasks/role_removal.yml
  tests/integration/targets/iam_role/tasks/tags_update.yml
Labels: mergeit
