Repository ansible-collections/community.aws, pull requests merged in 2023-11, with the labels that each got.

#1991 Update docs links to use stable-7
  README.md
  docs/docsite/links.yml
  galaxy.yml
Labels: mergeit

#1992 Prep community.aws 7.0.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1832-mq_broker_tags.yml
  changelogs/fragments/1891_ecs-task-definition-add-runtime-platform.yml
  changelogs/fragments/1904-route53_wait.yml
  changelogs/fragments/1962-isort.yml
  changelogs/fragments/20230623-black-cloudfront.yml
  changelogs/fragments/20230702-isort.yml
  changelogs/fragments/20230801-fix-linters.yml
  changelogs/fragments/20230906-galaxy.yml
  changelogs/fragments/20230906-route53_wait.yml
  changelogs/fragments/20230908-alias-cleanup.yml
  changelogs/fragments/20230915_migrate_iam_role_and_iam_role_info.yml
  changelogs/fragments/7.0.0-dev0.yml
  changelogs/fragments/botocore.yml
  changelogs/fragments/botocore_params-cleanup.yml
  changelogs/fragments/eks_nodegroup-integration-wait-delete.yml
  changelogs/fragments/galaxy_importer.yml
  changelogs/fragments/migrate_aws_region_info.yml
  changelogs/fragments/migrate_iam_access_key.yml
  changelogs/fragments/migrate_iam_group.yml
  changelogs/fragments/migrate_iam_managed_policy.yml
  changelogs/fragments/migrate_iam_mfa_device_info.yml
  changelogs/fragments/migrate_iam_password_policy.yml
  changelogs/fragments/migrate_s3_bucket_info.yml
  changelogs/fragments/migrate_sts_assume_role.yml
  changelogs/fragments/opensearch_domainconfig_no_options.yaml
  changelogs/fragments/python37.yml
  changelogs/fragments/workflow-requirements.yml
  galaxy.yml
  plugins/module_utils/common.py
  tests/integration/targets/eks_nodegroup/aliases
Labels: mergeit, skip-changelog

#2000 [stable-6] Lock sanity test versions based on what we were testing when 7.0.0 was released
  .github/workflows/sanity.yml
  .github/workflows/units.yml
Labels: mergeit

#1999 Update sanity tests - upstream no longer supports ansible 2.9
  .github/workflows/sanity.yml
  .github/workflows/units.yml
  test-requirements.txt
  tests/integration/requirements.txt
Labels: mergeit, backport-7

#2004 setup_sshkey: drop a dep on Crypto
  test-requirements.txt
  tests/integration/requirements.txt
  tests/integration/targets/setup_sshkey/files/ec2-fingerprint.py
Labels: mergeit, backport-7
