Repository ansible-collections/community.aws, pull requests merged in 2023-12, with the labels that each got.

#2013 fix unsafe asserts
  tests/integration/targets/api_gateway_domain/tasks/main.yml
  tests/integration/targets/autoscaling_instance_refresh/tasks/main.yml
  tests/integration/targets/autoscaling_policy/tasks/main.yml
  tests/integration/targets/autoscaling_scheduled_action/tasks/main.yml
  tests/integration/targets/cloudfront_distribution/tasks/main.yml
  tests/integration/targets/cloudfront_reponse_headers_policy/task/main.yml
  tests/integration/targets/codecommit_repository/tasks/main.yml
  tests/integration/targets/codepipeline/tasks/main.yml
  tests/integration/targets/connection/test_assume.yml
  tests/integration/targets/ec2_placement_group/tasks/main.yml
  tests/integration/targets/ecs_cluster/tasks/20_ecs_service.yml
  tests/integration/targets/ecs_ecr/tasks/main.yml
  tests/integration/targets/ecs_tag/tasks/main.yml
  tests/integration/targets/efs/tasks/main.yml
  tests/integration/targets/elasticache/tasks/main.yml
  tests/integration/targets/elb_classic_lb_info/tasks/main.yml
  tests/integration/targets/elb_network_lb/tasks/test_nlb_tags.yml
  tests/integration/targets/elb_target/tasks/ec2_target.yml
  tests/integration/targets/elb_target_info/tasks/main.yml
  tests/integration/targets/inventory_aws_mq/playbooks/test_inventory_with_hostvars_prefix_suffix.yml
  tests/integration/targets/inventory_aws_mq/playbooks/test_populating_inventory.yml
  tests/integration/targets/lightsail/tasks/main.yml
  tests/integration/targets/lightsail_snapshot/tasks/main.yml
  tests/integration/targets/msk_cluster-auth/tasks/test_create_auth.yml
  tests/integration/targets/msk_cluster/tasks/test_create.yml
  tests/integration/targets/msk_config/tasks/main.yml
  tests/integration/targets/redshift/tasks/main.yml
  tests/integration/targets/s3_sync/tasks/main.yml
  tests/integration/targets/sns_topic/tasks/main.yml
  tests/integration/targets/sqs_queue/tasks/main.yml
  tests/integration/targets/ssm_parameter/tasks/main.yml
  tests/integration/targets/stepfunctions_state_machine/tasks/main.yml
  tests/integration/targets/waf_web_acl/tasks/main.yml
Labels: mergeit, backport-6, backport-7

#2010 elb_network_lb - add support for AlpnPolicy for TLS listeners
  changelogs/fragments/20231127-elb_network_lb-update-tls-listeners.yaml
  plugins/modules/elb_network_lb.py
  tests/integration/targets/elb_network_lb/tasks/test_modifying_nlb_listeners.yml
Labels: mergeit

#2017 stable-6: add upper limit for amazon.aws dependency
  galaxy.yml
Labels: mergeit

#2024 Fix broken sanity tests
  .github/workflows/sanity.yml
Labels: mergeit, skip-changelog

#2021 New module dynamodb_table_info
  meta/runtime.yml
  plugins/modules/dynamodb_table_info.py
  tests/integration/targets/dynamodb_table/tasks/main.yml
  tests/integration/targets/dynamodb_table/tasks/test_pay_per_request.yml
Labels: mergeit, skip-changelog
