Repository ansible-collections/community.aws, pull requests merged in 2024-05, with the labels that each got.

#2082 Bump 2024 deprecations from dates to release versions
  changelogs/fragments/9-date-deprecations.yml
  plugins/modules/ecs_cluster.py
  plugins/modules/ecs_service.py
  plugins/modules/glue_connection.py
Labels: mergeit

#2092 Update docs-links for stable-8 branch
  README.md
  docs/docsite/links.yml
Labels: mergeit

#2093 Support for ansible-core < 2.15 has been dropped
  README.md
  changelogs/fragments/8.0.0-increase-ansible-core-version.yml
  meta/runtime.yml
Labels: mergeit, skip-changelog, backport-8

#2097 Prep release 8.0.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1832-mq_broker_tags.yml
  changelogs/fragments/1891_ecs-task-definition-add-runtime-platform.yml
  changelogs/fragments/1904-route53_wait.yml
  changelogs/fragments/1962-isort.yml
  changelogs/fragments/20230623-black-cloudfront.yml
  changelogs/fragments/20230702-isort.yml
  changelogs/fragments/20230801-fix-linters.yml
  changelogs/fragments/20230906-galaxy.yml
  changelogs/fragments/20230906-route53_wait.yml
  changelogs/fragments/20230908-alias-cleanup.yml
  changelogs/fragments/20230915_migrate_iam_role_and_iam_role_info.yml
  changelogs/fragments/20231127-elb_network_lb-update-tls-listeners.yaml
  changelogs/fragments/20240408-efs-sanity_fix.yml
  changelogs/fragments/7.0.0-dev0.yml
  changelogs/fragments/8.0.0-increase-ansible-core-version.yml
  changelogs/fragments/9-date-deprecations.yml
  changelogs/fragments/boto3_equals.yml
  changelogs/fragments/botocore.yml
  changelogs/fragments/botocore_params-cleanup.yml
  changelogs/fragments/eks_nodegroup-integration-wait-delete.yml
  changelogs/fragments/galaxy_importer.yml
  changelogs/fragments/migrate_aws_region_info.yml
  changelogs/fragments/migrate_iam_access_key.yml
  changelogs/fragments/migrate_iam_group.yml
  changelogs/fragments/migrate_iam_managed_policy.yml
  changelogs/fragments/migrate_iam_mfa_device_info.yml
  changelogs/fragments/migrate_iam_password_policy.yml
  changelogs/fragments/migrate_s3_bucket_info.yml
  changelogs/fragments/migrate_sts_assume_role.yml
  changelogs/fragments/opensearch_domainconfig_no_options.yaml
  changelogs/fragments/python37.yml
  changelogs/fragments/workflow-requirements.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2098 Changelog updates after 8.0.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1832-mq_broker_tags.yml
  changelogs/fragments/1891_ecs-task-definition-add-runtime-platform.yml
  changelogs/fragments/1904-route53_wait.yml
  changelogs/fragments/1962-isort.yml
  changelogs/fragments/20230623-black-cloudfront.yml
  changelogs/fragments/20230702-isort.yml
  changelogs/fragments/20230801-fix-linters.yml
  changelogs/fragments/20230906-galaxy.yml
  changelogs/fragments/20230906-route53_wait.yml
  changelogs/fragments/20230908-alias-cleanup.yml
  changelogs/fragments/20230915_migrate_iam_role_and_iam_role_info.yml
  changelogs/fragments/20231127-elb_network_lb-update-tls-listeners.yaml
  changelogs/fragments/20240408-efs-sanity_fix.yml
  changelogs/fragments/7.0.0-dev0.yml
  changelogs/fragments/8.0.0-increase-ansible-core-version.yml
  changelogs/fragments/9-date-deprecations.yml
  changelogs/fragments/boto3_equals.yml
  changelogs/fragments/botocore.yml
  changelogs/fragments/botocore_params-cleanup.yml
  changelogs/fragments/eks_nodegroup-integration-wait-delete.yml
  changelogs/fragments/galaxy_importer.yml
  changelogs/fragments/migrate_aws_region_info.yml
  changelogs/fragments/migrate_iam_access_key.yml
  changelogs/fragments/migrate_iam_group.yml
  changelogs/fragments/migrate_iam_managed_policy.yml
  changelogs/fragments/migrate_iam_mfa_device_info.yml
  changelogs/fragments/migrate_iam_password_policy.yml
  changelogs/fragments/migrate_s3_bucket_info.yml
  changelogs/fragments/migrate_sts_assume_role.yml
  changelogs/fragments/opensearch_domainconfig_no_options.yaml
  changelogs/fragments/python37.yml
  changelogs/fragments/workflow-requirements.yml
Labels: mergeit

#2101 msk_cluster - disable integration tests
  changelogs/fragments/20240423-msk_cluster-disable-tests.yml
  tests/integration/targets/msk_cluster/aliases
Labels: mergeit, backport-8
