Repository ansible-collections/community.aws, pull requests merged in 2024-04, with the labels that each got.

#2065 Update lambda python runtime version in integration tests
  changelogs/fragments/20240402-lambda-test-runtime.yml
  tests/integration/targets/elb_target/tasks/lambda_target.yml
  tests/integration/targets/s3_bucket_notification/tasks/test_lambda_notifications.yml
  tests/integration/targets/secretsmanager_secret/tasks/rotation.yml
  tests/integration/targets/sns_topic/tasks/main.yml
Labels: mergeit, backport-6, backport-7

#2064 Prep community.aws 7.2.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1908-fix_find_out_bucket_region_logic.yml
  changelogs/fragments/1947-add_support_msk_addtinal_type.yml
  changelogs/fragments/20240402-lambda-test-runtime.yml
  changelogs/fragments/2048-add-new-instance-types-in-gluejob.yaml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2070 amazon.aws 8.0.0 deprecations - test cleanup
  tests/integration/targets/config/tasks/main.yaml
  tests/integration/targets/ec2_launch_template/tasks/iam_instance_role.yml
  tests/integration/targets/ecs_cluster/tasks/20_ecs_service.yml
  tests/integration/targets/eks_cluster/tasks/full_test.yml
  tests/integration/targets/eks_fargate_profile/tasks/create_eks_cluster.yml
  tests/integration/targets/eks_fargate_profile/tasks/full_test.yml
  tests/integration/targets/eks_nodegroup/tasks/dependecies.yml
  tests/integration/targets/eks_nodegroup/tasks/full_test.yml
Labels: mergeit, skip-changelog

#2069 Changelog update after 7.2.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1908-fix_find_out_bucket_region_logic.yml
  changelogs/fragments/1947-add_support_msk_addtinal_type.yml
  changelogs/fragments/20240402-lambda-test-runtime.yml
  changelogs/fragments/2048-add-new-instance-types-in-gluejob.yaml
Labels: mergeit

#2071 efs - Use `yield from` in order to fix sanity errors
  changelogs/fragments/20240408-efs-sanity_fix.yml
  plugins/modules/efs.py
Labels: mergeit

#2074 Drop support for ansible-core < 2.14
  README.md
  changelogs/fragments/8.0.0-increase-ansible-core-version.yml
  meta/runtime.yml
Labels: mergeit, do_not_backport

#2075 Remove use of ignored boto3 parameter
  changelogs/fragments/boto3_equals.yml
  plugins/modules/autoscaling_launch_config.py
  plugins/modules/glue_connection.py
Labels: mergeit, backport-7
