Repository ansible-collections/community.aws, pull requests merged in 2024-07, with the labels that each got.

#2112 Adjust docs publish workflow
  .github/workflows/docs-push.yml
Labels: mergeit, backport-3, backport-4, backport-5, backport-6, backport-7, backport-8

#2063 Add support to enable multicast on transit gateway
  changelogs/fragments/2063-add-multicast-support.yml
  plugins/module_utils/transitgateway.py
  plugins/modules/ec2_transit_gateway.py
  plugins/modules/ec2_transit_gateway_info.py
  tests/integration/targets/ec2_transit_gateway/tasks/main.yml
Labels: mergeit, backport-8

#2122 Update eks_nodegroup test to use t3a.micro
  tests/integration/targets/eks_nodegroup/aliases
  tests/integration/targets/eks_nodegroup/tasks/dependecies.yml
  tests/integration/targets/eks_nodegroup/tasks/full_test.yml
  tests/integration/targets/eks_nodegroup/tasks/main.yml
Labels: mergeit
