Repository ansible-collections/community.aws, pull requests merged in 2024-10, with the labels that each got.

#2152 Prepare modules ec2_vpc_egress_igw for promotion
  changelogs/fragments/20240923-refactor-ec2_vpc_egress_igw-modules.yml
  plugins/modules/ec2_vpc_egress_igw.py
  tests/integration/targets/ec2_vpc_egress_igw/meta/main.yml
  tests/integration/targets/ec2_vpc_egress_igw/tasks/main.yml
Labels: mergeit

#2163 DNM Migrate elb_classic_lb_info* modules and tests
  changelogs/fragments/2139-elb_classic_lb_info-refactor-module.yml
  changelogs/fragments/migrate_elb_classic_lb_info.yml
  meta/runtime.yml
  plugins/modules/elb_classic_lb_info.py
  tests/integration/targets/elb_classic_lb_info/aliases
  tests/integration/targets/elb_classic_lb_info/defaults/main.yml
  tests/integration/targets/elb_classic_lb_info/meta/main.yml
  tests/integration/targets/elb_classic_lb_info/tasks/main.yml
  tests/integration/targets/elb_classic_lb_info/vars/main.yml
Labels: mergeit

#2170 Revert "DNM Migrate elb_classic_lb_info* modules and tests (#2163)"
  changelogs/fragments/2139-elb_classic_lb_info-refactor-module.yml
  changelogs/fragments/migrate_elb_classic_lb_info.yml
  meta/runtime.yml
  plugins/modules/elb_classic_lb_info.py
  tests/integration/targets/elb_classic_lb_info/aliases
  tests/integration/targets/elb_classic_lb_info/defaults/main.yml
  tests/integration/targets/elb_classic_lb_info/meta/main.yml
  tests/integration/targets/elb_classic_lb_info/tasks/main.yml
  tests/integration/targets/elb_classic_lb_info/vars/main.yml
Labels: mergeit

#2153 Refactor ec2_vpc_peer* modules
  changelogs/fragments/20240924-ec2_vpc_peer-refactor.yml
  plugins/modules/ec2_vpc_peer.py
  plugins/modules/ec2_vpc_peering_info.py
  tests/integration/targets/ec2_vpc_peer/tasks/main.yml
Labels: mergeit

#2159 Prepare modules ec2_vpc_nacl and ec2_vpc_nacl_info for promotion
  changelogs/fragments/20240924-refactor-ec2_vpc_nacl-modules.yaml
  plugins/modules/ec2_vpc_nacl.py
  plugins/modules/ec2_vpc_nacl_info.py
  tests/integration/targets/ec2_vpc_nacl/tasks/ingress_and_egress.yml
  tests/integration/targets/ec2_vpc_nacl/tasks/ipv6.yml
  tests/integration/targets/ec2_vpc_nacl/tasks/main.yml
  tests/integration/targets/ec2_vpc_nacl/tasks/subnet_ids.yml
  tests/integration/targets/ec2_vpc_nacl/tasks/subnet_names.yml
  tests/integration/targets/ec2_vpc_nacl/tasks/tags.yml
Labels: mergeit

#2160 Refactor ec2_vpc_vpn* modules
  changelogs/fragments/20240930-ec2_vpc_vpn_refactoring.yml
  plugins/modules/ec2_vpc_vpn.py
  plugins/modules/ec2_vpc_vpn_info.py
  tests/integration/targets/ec2_vpc_vpn/tasks/main.yml
  tests/integration/targets/ec2_vpc_vpn/tasks/tags.yml
  tests/unit/plugins/modules/test_ec2_vpc_vpn.py
Labels: mergeit

#2167 Prepare ec2_placement_group* module for promotion
  changelogs/fragments/refactor_ec2_placement_group.yml
  plugins/modules/ec2_placement_group.py
  plugins/modules/ec2_placement_group_info.py
  tests/integration/targets/ec2_placement_group/tasks/env_cleanup.yml
  tests/integration/targets/ec2_placement_group/tasks/env_setup.yml
  tests/integration/targets/ec2_placement_group/tasks/main.yml
Labels: mergeit

#2157 ec2_transit_gateway_vpc_attachment - Prepare module for migration to amazon.aws
  changelogs/fragments/20240924-fix-documentation-tgw-vpc-att.yml
  plugins/module_utils/transitgateway.py
  plugins/modules/ec2_transit_gateway_vpc_attachment.py
  plugins/modules/ec2_transit_gateway_vpc_attachment_info.py
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/tasks/cleanup.yml
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/tasks/complex.yml
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/tasks/setup.yml
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/tasks/simple.yml
Labels: mergeit

#2164 Prepare module ec2_launch_template for promotion
  changelogs/fragments/20240110-ec2_launch_template-refactor.yml
  plugins/modules/ec2_launch_template.py
  tests/integration/targets/ec2_launch_template/aliases
  tests/integration/targets/ec2_launch_template/tasks/cpu_options.yml
  tests/integration/targets/ec2_launch_template/tasks/deletion.yml
  tests/integration/targets/ec2_launch_template/tasks/iam_instance_role.yml
  tests/integration/targets/ec2_launch_template/tasks/instance-metadata.yml
  tests/integration/targets/ec2_launch_template/tasks/main.yml
  tests/integration/targets/ec2_launch_template/tasks/network_interfaces.yml
  tests/integration/targets/ec2_launch_template/tasks/tagging.yml
  tests/integration/targets/ec2_launch_template/tasks/tags_and_vpc_settings.yml
  tests/integration/targets/ec2_launch_template/tasks/template_data.yml
  tests/integration/targets/ec2_launch_template/tasks/versions.yml
Labels: mergeit

#2171 Prepare ec2_vpc_vgw_* modules for promotion
  changelogs/fragments/refactor-ec2_vpc_vgw-modules.yml
  plugins/modules/ec2_vpc_vgw.py
  plugins/modules/ec2_vpc_vgw_info.py
  tests/integration/targets/ec2_vpc_vgw/tasks/main.yml
  tests/integration/targets/ec2_vpc_vgw/tasks/tags.yml
Labels: mergeit

#2158 Refactor ec2_transit_gateway_* modules
  changelogs/fragments/refactor-ec2_transit_gateway-modules.yml
  plugins/modules/ec2_transit_gateway.py
  plugins/modules/ec2_transit_gateway_info.py
  tests/integration/targets/ec2_transit_gateway/tasks/main.yml
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/tasks/setup.yml
Labels: mergeit

#2187 Use `ansible-ref: devel` for docs build workflows
  .github/workflows/docs-pr.yml
  .github/workflows/docs-push.yml
Labels: mergeit

#2169 DNM - Migrate modules ec2_vpc_egress_igw and tests
  changelogs/fragments/migrate_ec2_vpc_egress_igw.yml
  meta/runtime.yml
  plugins/modules/ec2_vpc_egress_igw.py
  tests/integration/targets/ec2_vpc_egress_igw/aliases
  tests/integration/targets/ec2_vpc_egress_igw/tasks/main.yml
Labels: mergeit

#2184 DNM Promote ec2_transit_gateway_vpc_attachment and ec2_transit_gateway_vpc_attachment_info modules and tests
  changelogs/fragments/migrate_ec2_transit_gateway_vpc_attachment.yml
  meta/runtime.yml
  plugins/module_utils/transitgateway.py
  plugins/modules/ec2_transit_gateway_vpc_attachment.py
  plugins/modules/ec2_transit_gateway_vpc_attachment_info.py
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/aliases
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/defaults/main.yml
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/meta/main.yml
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/tasks/cleanup.yml
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/tasks/complex.yml
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/tasks/main.yml
  tests/integration/targets/ec2_transit_gateway_vpc_attachment/tasks/simple.yml
Labels: mergeit

#2186 DNM Promote elb_classic_lb_info to amazon.aws
  changelogs/fragments/migrate_elb_classic_lb_info.yml
  meta/runtime.yml
  plugins/modules/elb_classic_lb_info.py
  tests/integration/targets/elb_classic_lb_info/aliases
  tests/integration/targets/elb_classic_lb_info/defaults/main.yml
  tests/integration/targets/elb_classic_lb_info/meta/main.yml
  tests/integration/targets/elb_classic_lb_info/tasks/main.yml
  tests/integration/targets/elb_classic_lb_info/vars/main.yml
Labels: mergeit

#2178 DNM - Migrate modules ec2_vpc_nacl,ec2_vpc_nacl_info and tests
  changelogs/fragments/migrate_ec2_vpc_nacl_ec2_vpc_nacl_info.yaml
  meta/runtime.yml
  plugins/modules/ec2_vpc_nacl.py
  plugins/modules/ec2_vpc_nacl_info.py
  tests/integration/targets/ec2_vpc_nacl/aliases
  tests/integration/targets/ec2_vpc_nacl/defaults/main.yml
  tests/integration/targets/ec2_vpc_nacl/meta/main.yml
  tests/integration/targets/ec2_vpc_nacl/tasks/ingress_and_egress.yml
  tests/integration/targets/ec2_vpc_nacl/tasks/ipv6.yml
  tests/integration/targets/ec2_vpc_nacl/tasks/main.yml
  tests/integration/targets/ec2_vpc_nacl/tasks/subnet_ids.yml
  tests/integration/targets/ec2_vpc_nacl/tasks/subnet_names.yml
  tests/integration/targets/ec2_vpc_nacl/tasks/tags.yml
Labels: mergeit

#2181 DNM Promote ec2_placement_group* to amazon.aws
  changelogs/fragments/migrate_ec2_placement_group.yml
  meta/runtime.yml
  plugins/modules/ec2_placement_group.py
  plugins/modules/ec2_placement_group_info.py
  tests/integration/targets/ec2_placement_group/aliases
  tests/integration/targets/ec2_placement_group/defaults/main.yml
  tests/integration/targets/ec2_placement_group/meta/main.yml
  tests/integration/targets/ec2_placement_group/tasks/env_cleanup.yml
  tests/integration/targets/ec2_placement_group/tasks/env_setup.yml
  tests/integration/targets/ec2_placement_group/tasks/main.yml
  tests/integration/targets/ec2_placement_group/vars/main.yml
Labels: mergeit

#2185 DNM - Migrate modules ec2_launch_template and tests
  changelogs/fragments/migrate_ec2_launch_template.yaml
  meta/runtime.yml
  plugins/modules/ec2_launch_template.py
  tests/integration/targets/ec2_launch_template/aliases
  tests/integration/targets/ec2_launch_template/defaults/main.yml
  tests/integration/targets/ec2_launch_template/files/assume-role-policy.json
  tests/integration/targets/ec2_launch_template/meta/main.yml
  tests/integration/targets/ec2_launch_template/tasks/deletion.yml
  tests/integration/targets/ec2_launch_template/tasks/iam_instance_role.yml
  tests/integration/targets/ec2_launch_template/tasks/main.yml
  tests/integration/targets/ec2_launch_template/tasks/tagging.yml
  tests/integration/targets/ec2_launch_template/tasks/template_data.yml
  tests/integration/targets/ec2_launch_template/tasks/versions.yml
Labels: mergeit

#2190 DNM Promote ec2_vpc_vgw and ec2_vpc_vgw_info modules and tests
  changelogs/fragments/migrate_ec2_vpc_vgw.yml
  meta/runtime.yml
  plugins/modules/ec2_vpc_vgw.py
  plugins/modules/ec2_vpc_vgw_info.py
  tests/integration/targets/ec2_vpc_vgw/aliases
  tests/integration/targets/ec2_vpc_vgw/defaults/main.yml
  tests/integration/targets/ec2_vpc_vgw/meta/main.yml
  tests/integration/targets/ec2_vpc_vgw/tasks/main.yml
  tests/integration/targets/ec2_vpc_vgw/tasks/tags.yml
Labels: mergeit

#2177 DNM - Migrate modules autoscaling_instance_refresh,autoscaling_instance_refresh_info and tests
  changelogs/fragments/migrate_autoscaling_instance_refresh_autoscaling_instance_refresh_info.yaml
  meta/runtime.yml
  plugins/modules/autoscaling_instance_refresh.py
  plugins/modules/autoscaling_instance_refresh_info.py
  tests/integration/targets/autoscaling_instance_refresh/aliases
  tests/integration/targets/autoscaling_instance_refresh/defaults/main.yml
  tests/integration/targets/autoscaling_instance_refresh/meta/main.yml
  tests/integration/targets/autoscaling_instance_refresh/tasks/instance_refresh_info.yml
  tests/integration/targets/autoscaling_instance_refresh/tasks/main.yml
  tests/integration/targets/autoscaling_instance_refresh/tasks/refresh_and_cancel_three_times.yml
  tests/integration/targets/autoscaling_instance_refresh/tasks/start_cancel_instance_refresh.yml
  tests/unit/plugins/modules/test_autoscaling_instance_refresh.py
Labels: mergeit

#2189 DNM Migrate ec2_transit_gateway_info modules and tests
  changelogs/fragments/migrate_ec2_transit_gateway_info.yml
  meta/runtime.yml
  plugins/modules/ec2_transit_gateway_info.py
Labels: mergeit

#2192 DNM Migrate ec2_transit_gateway module and tests
  changelogs/fragments/migrate_ec2_transit_gateway.yml
  meta/runtime.yml
  plugins/modules/ec2_transit_gateway.py
  tests/integration/targets/ec2_transit_gateway/aliases
  tests/integration/targets/ec2_transit_gateway/meta/main.yml
  tests/integration/targets/ec2_transit_gateway/tasks/main.yml
Labels: mergeit

#2165 Drop deprecated options
  changelogs/fragments/20241007-drop_deprecations.yml
  plugins/modules/ecs_cluster.py
  plugins/modules/glue_connection.py
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
  tests/sanity/ignore-2.18.txt
  tests/sanity/ignore-2.19.txt
Labels: mergeit

#2194 Links update after branching stable-9
  README.md
  changelogs/fragments/20241029-update-docs.yml
  docs/docsite/links.yml
Labels: mergeit

#2195 Bump botocore/boto3 requirements (add deprecation reminder about Python 3.8 support
  README.md
  changelogs/fragments/botocore-python.yaml
  plugins/modules/ecs_service.py
  requirements.txt
  tests/integration/constraints.txt
  tests/unit/constraints.txt
Labels: mergeit, backport-9

#2198 Fix broken SES integration tests
  tests/integration/targets/ses_identity/tasks/main.yaml
Labels: mergeit, skip-changelog, backport-9

#2197 Prep community.aws 9.0.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/0-readme.yml
  changelogs/fragments/20240110-ec2_launch_template-refactor.yml
  changelogs/fragments/20240423-msk_cluster-disable-tests.yml
  changelogs/fragments/20240613_ec2_placement_group_tags.yml
  changelogs/fragments/20240909-ec2_vpc_vgw-fix-super-exception.yaml
  changelogs/fragments/20240919-fix_sanity.yml
  changelogs/fragments/20240920-refactor-autoscaling_instance_refresh-modules.yml
  changelogs/fragments/20240923-refactor-ec2_vpc_egress_igw-modules.yml
  changelogs/fragments/20240924-create-ignore-2.19.yml
  changelogs/fragments/20240924-ec2_vpc_peer-refactor.yml
  changelogs/fragments/20240924-fix-documentation-tgw-vpc-att.yml
  changelogs/fragments/20240924-refactor-ec2_vpc_nacl-modules.yaml
  changelogs/fragments/20240930-ec2_vpc_vpn_refactoring.yml
  changelogs/fragments/20241007-drop_deprecations.yml
  changelogs/fragments/20241029-update-docs.yml
  changelogs/fragments/20250515-main-9.0.0.yml
  changelogs/fragments/2063-add-multicast-support.yml
  changelogs/fragments/2124-add-retry-to-ecs_taskdefinition.yml
  changelogs/fragments/2139-elb_classic_lb_info-refactor-module.yml
  changelogs/fragments/2142-elb_network_lb-update-tests-to-use-valid-cert.yml
  changelogs/fragments/botocore-python.yaml
  changelogs/fragments/migrate_autoscaling_instance_refresh_autoscaling_instance_refresh_info.yaml
  changelogs/fragments/migrate_ec2_launch_template.yaml
  changelogs/fragments/migrate_ec2_placement_group.yml
  changelogs/fragments/migrate_ec2_transit_gateway.yml
  changelogs/fragments/migrate_ec2_transit_gateway_info.yml
  changelogs/fragments/migrate_ec2_transit_gateway_vpc_attachment.yml
  changelogs/fragments/migrate_ec2_vpc_egress_igw.yml
  changelogs/fragments/migrate_ec2_vpc_nacl_ec2_vpc_nacl_info.yaml
  changelogs/fragments/migrate_ec2_vpc_peer.yml
  changelogs/fragments/migrate_ec2_vpc_vgw.yml
  changelogs/fragments/migrate_ec2_vpc_vpn.yml
  changelogs/fragments/migrate_elb_classic_lb_info.yml
  changelogs/fragments/refactor-ec2_transit_gateway-modules.yml
  changelogs/fragments/refactor-ec2_vpc_vgw-modules.yml
  changelogs/fragments/refactor_ec2_placement_group.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2193 Bump release for main branch to 10.0.0-dev0
  changelogs/fragments/20241029-main-10.0.0.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit
