Repository ansible-collections/community.aws, pull requests merged in 2025-02, with the labels that each got.

#2228 [PR #2219/cfdcc05 backport][stable-9] Cleanup tox configs and unit tests (#2219)
  pyproject.toml
  tests/unit/conftest.py
  tests/unit/plugins/conftest.py
  tests/unit/plugins/modules/conftest.py
  tests/unit/plugins/modules/dms_endpoint/test_compare_params.py
  tests/unit/plugins/modules/test_data_pipeline.py
  tests/unit/plugins/modules/test_directconnect_connection.py
  tests/unit/plugins/modules/test_directconnect_link_aggregation_group.py
  tests/unit/plugins/modules/test_directconnect_virtual_interface.py
  tox.ini
Labels: mergeit

#2226 connection/aws_ssm - refactor exec_command function to improve maintanability
  changelogs/fragments/20250130-aws_ssm-refactor-exec_command.yaml
  plugins/connection/aws_ssm.py
  tests/unit/plugins/connection/aws_ssm/conftest.py
  tests/unit/plugins/connection/aws_ssm/test_aws_ssm.py
  tests/unit/plugins/connection/aws_ssm/test_exec_command.py
Labels: mergeit, backport-9

#2234 Update connection/aws_ssm documentation
  plugins/connection/aws_ssm.py
Labels: mergeit, skip-changelog, backport-9

#2235 Add generate_mark() function and corresponding unit test.
  changelogs/fragments/2096-refactor-random-helper-function.yml
  plugins/connection/aws_ssm.py
  tests/unit/plugins/connection/aws_ssm/test_aws_ssm.py
Labels: mergeit, backport-9

#2238 disable redshift tests
  tests/integration/targets/redshift/aliases
Labels: mergeit, backport-9

#2229 aws_ssm - refactor _prepare_terminal() method
  changelogs/fragments/20250204-aws_ssm-refactor-prepare_terminal.yml
  plugins/connection/aws_ssm.py
  tests/unit/plugins/connection/aws_ssm/conftest.py
  tests/unit/plugins/connection/aws_ssm/test_prepare_terminal.py
Labels: mergeit, backport-9

#2247 connection/aws_ssm - support environment variable for aws_ssm_plugin variable
  .gitignore
  changelogs/fragments/20250217-connection-aws_ssm-add-env-variable-for-aws_ssm_plugin.yaml
  plugins/connection/aws_ssm.py
  tests/unit/plugins/connection/aws_ssm/test_get_executable.py
Labels: mergeit, backport-9

#2252 Fix sanity after merge of #2247
  tests/unit/plugins/connection/aws_ssm/test_get_executable.py
Labels: mergeit, skip-changelog, backport-9

#2256 Prep `community.aws` 9.1.0 Release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1979-use-headbucket.yml
  changelogs/fragments/20240426_fix_ssm_clixml.yml
  changelogs/fragments/20250127-pylint.yml
  changelogs/fragments/20250127-waf_confition.yml
  changelogs/fragments/20250130-aws_ssm-refactor-exec_command.yaml
  changelogs/fragments/20250204-aws_ssm-refactor-prepare_terminal.yml
  changelogs/fragments/20250217-connection-aws_ssm-add-env-variable-for-aws_ssm_plugin.yaml
  changelogs/fragments/2096-refactor-random-helper-function.yml
  changelogs/fragments/2205-support-minmax-s3lifecycle.yml
  changelogs/fragments/refactor_ssm_init_client.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog
