Repository ansible-collections/community.aws, pull requests merged in 2025-04, with the labels that each got.

#2271 Prep community.aws 9.2.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2248-aws_ssm-refactor-command-related-methods.yml
  changelogs/fragments/2255-aws_ssm-refactor-create-s3clientmanager-class.yml
  changelogs/fragments/2264-aws_ssm_refactor_verbosity_display.yaml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2270 connection/aws_ssm - create TerminalManager class and move related methods
  changelogs/fragments/2270-aws_ssm-refactor-create-terminalmanager-class.yml
  plugins/connection/aws_ssm.py
  plugins/plugin_utils/terminalmanager.py
  tests/unit/plugins/connection/aws_ssm/test_exec_command.py
  tests/unit/plugins/connection/aws_ssm/test_prepare_terminal.py
Labels: mergeit, backport-9

#2275 refactor connection/aws_ssm plugin
  changelogs/fragments/20250104-refactor-connection-aws_ssm-s3-operation.yml
  plugins/connection/aws_ssm.py
  plugins/plugin_utils/base.py
  plugins/plugin_utils/s3clientmanager.py
  tests/unit/plugins/connection/aws_ssm/test_aws_ssm.py
Labels: mergeit, backport-9

#2272 Refactor connection/aws_ssm plugin
  changelogs/fragments/20250326-connection_aws_ssm-refactor-session-manager.yml
  plugins/connection/aws_ssm.py
  plugins/plugin_utils/ssmsessionmanager.py
  plugins/plugin_utils/terminalmanager.py
  tests/unit/plugins/connection/aws_ssm/conftest.py
  tests/unit/plugins/connection/aws_ssm/test_aws_ssm.py
  tests/unit/plugins/connection/aws_ssm/test_exec_command.py
  tests/unit/plugins/connection/aws_ssm/test_prepare_terminal.py
  tests/unit/plugins/connection/aws_ssm/test_ssm_session_manager.py
Labels: mergeit, backport-9

#2279 Move the aws_ssm connection plugin's plugin_utils into a dedicated folder
  changelogs/fragments/20250408-aws_ssm-plugin_utils.yml
  plugins/connection/aws_ssm.py
  plugins/plugin_utils/ssm/base.py
  plugins/plugin_utils/ssm/s3clientmanager.py
  plugins/plugin_utils/ssm/sessionmanager.py
  plugins/plugin_utils/ssm/terminalmanager.py
  tests/unit/plugins/connection/aws_ssm/test_aws_ssm.py
  tests/unit/plugins/connection/aws_ssm/test_prepare_terminal.py
  tests/unit/plugins/connection/aws_ssm/test_ssm_session_manager.py
Labels: mergeit, backport-9

#2274 Update main branch after releasing community.aws 9.2.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2248-aws_ssm-refactor-command-related-methods.yml
  changelogs/fragments/2255-aws_ssm-refactor-create-s3clientmanager-class.yml
  changelogs/fragments/2264-aws_ssm_refactor_verbosity_display.yaml
Labels: mergeit, do_not_backport, skip-changelog

#2284 Update test set_module_args for compatibility with new patching method
  tests/unit/plugins/modules/utils.py
Labels: mergeit, skip-changelog, backport-9

#2285 Fix integration on devel branch (data tagging)
  tests/integration/targets/ecs_ecr/tasks/main.yml
  tests/integration/targets/efs/aliases
  tests/integration/targets/efs/tasks/main.yml
  tests/integration/targets/elb_target/tasks/ec2_target.yml
  tests/integration/targets/lightsail_static_ip/tasks/main.yml
  tests/integration/targets/route53_wait/tasks/main.yml
  tests/integration/targets/ses_identity/aliases
  tests/integration/targets/ses_identity/tasks/assert_defaults.yaml
  tests/integration/targets/ses_identity/tasks/main.yaml
  tests/integration/targets/setup_connection_aws_ssm/tasks/main.yml
  tests/integration/targets/sns_topic/aliases
  tests/integration/targets/sns_topic/files/sns_topic_lambda.py
  tests/integration/targets/sns_topic/tasks/main.yml
Labels: mergeit, test-all-the-targets, backport-9

#2273 aws_ssm - Add FileTransferManager class
  changelogs/fragments/aws_ssm_filetransfermanager.yml
  plugins/connection/aws_ssm.py
  plugins/plugin_utils/ssm/common.py
  plugins/plugin_utils/ssm/filetransfermanager.py
  tests/integration/targets/setup_connection_aws_ssm/tasks/ec2_infra_teardown.yml
  tests/integration/targets/setup_connection_aws_ssm/tasks/macos.yml
  tests/integration/targets/setup_connection_aws_ssm/templates/boto_config.j2
  tests/unit/plugins/connection/aws_ssm/test_aws_ssm.py
  tests/unit/plugins/connection/aws_ssm/test_exec_command.py
  tests/unit/plugins/connection/aws_ssm/test_file_transfer_manager.py
Labels: mergeit, backport-9

#2295 Update ansible-lint to 25.1.2
  changelogs/fragments/update_ansible-lint.yml
  tox.ini
Labels: mergeit, backport-9

#2299 redshift_info: removes jijna delimiters from example using failed_when
  plugins/modules/redshift_info.py
Labels: mergeit, skip-changelog, backport-8, backport-9
