Repository ansible-collections/community.aws, pull requests merged in 2025-01, with the labels that each got.

#2210 Add Github workflow that adds backport_failed label when automatic backports fail.
  .github/workflows/backports-check.yml
Labels: mergeit, skip-changelog

#2212 Fix unit tests
  tests/unit/plugins/modules/test_data_pipeline.py
  tests/unit/plugins/modules/test_directconnect_connection.py
  tests/unit/plugins/modules/test_directconnect_link_aggregation_group.py
  tests/unit/plugins/modules/test_directconnect_virtual_interface.py
Labels: mergeit

#2211 Integration tests Connection SSM
  tests/integration/targets/connection/test_connection.yml
  tests/integration/targets/connection_aws_ssm_amazon/aliases
  tests/integration/targets/connection_aws_ssm_amazon/aws_ssm_integration_test_setup.yml
  tests/integration/targets/connection_aws_ssm_amazon/runme.sh
  tests/integration/targets/connection_aws_ssm_centos/aliases
  tests/integration/targets/connection_aws_ssm_cross_region/aliases
  tests/integration/targets/connection_aws_ssm_encrypted_s3/aliases
  tests/integration/targets/connection_aws_ssm_endpoint/aliases
  tests/integration/targets/connection_aws_ssm_profile/aliases
  tests/integration/targets/connection_aws_ssm_ssm_document/aliases
  tests/integration/targets/connection_aws_ssm_ubuntu/aliases
  tests/integration/targets/connection_aws_ssm_vars/aliases
  tests/integration/targets/connection_aws_ssm_windows/aliases
  tests/integration/targets/setup_connection_aws_ssm/defaults/main.yml
  tests/integration/targets/setup_connection_aws_ssm/tasks/cleanup.yml
  tests/integration/targets/setup_connection_aws_ssm/tasks/debian.yml
  tests/integration/targets/setup_connection_aws_ssm/tasks/ec2_infra_setup.yml
  tests/integration/targets/setup_connection_aws_ssm/tasks/ec2_infra_teardown.yml
  tests/integration/targets/setup_connection_aws_ssm/tasks/macos.yml
  tests/integration/targets/setup_connection_aws_ssm/tasks/main.yml
  tests/integration/targets/setup_connection_aws_ssm/tasks/redhat.yml
  tests/integration/targets/setup_connection_aws_ssm/tasks/ssm_document.yml
  tests/integration/targets/setup_connection_aws_ssm/templates/inventory-combined.aws_ssm.j2
Labels: mergeit, skip-changelog, backport-9

#1987 Use HeadBucket instead of GetBucketLocation (#1979)
  changelogs/fragments/1979-use-headbucket.yml
  plugins/connection/aws_ssm.py
Labels: mergeit, backport-8, backport-9

#2080 Fix aws_ssm when Powershell uses CLIXML
  changelogs/fragments/20240426_fix_ssm_clixml.yml
  plugins/connection/aws_ssm.py
Labels: mergeit, backport-8, backport-9

#2220 waf_condition - adds missing options validation to filters
  changelogs/fragments/20250127-waf_confition.yml
  plugins/modules/waf_condition.py
Labels: mergeit, backport-9

#2225 GitHub Workflow - Add backport-labeller
  .github/workflows/backports.yml
Labels: mergeit, do_not_backport

#2219 Cleanup tox configs and unit tests
  pyproject.toml
  tests/unit/conftest.py
  tests/unit/plugins/conftest.py
  tests/unit/plugins/modules/conftest.py
  tests/unit/plugins/modules/dms_endpoint/test_compare_params.py
  tests/unit/plugins/modules/test_data_pipeline.py
  tests/unit/plugins/modules/test_directconnect_connection.py
  tests/unit/plugins/modules/test_directconnect_link_aggregation_group.py
  tests/unit/plugins/modules/test_directconnect_virtual_interface.py
  tox.ini
Labels: mergeit, backport-9

#2223 aws_ssm: Refactor _init_clients Method
  changelogs/fragments/refactor_ssm_init_client.yml
  plugins/connection/aws_ssm.py
  tests/unit/plugins/connection/test_aws_ssm.py
Labels: mergeit, backport-9
